#!/bin/bash
CC=gcc
CFLAGS=-w

if quackCompiler $1; then
    :
else
    echo "===ERROR==="
    exit
fi

FILENAME=$(basename "$1")
FILENAME="${FILENAME%.*}"
echo ${CC} Builtins.o ${FILENAME}.c ${CFLAGS} -o ${FILENAME}
${CC} Builtins.o ${FILENAME}.c ${CFLAGS} -o ${FILENAME}
echo ./${FILENAME}
./${FILENAME}
