#!/bin/bash
CC=gcc
CFLAGS=-w

# If everything compiled correctly generate c code, else stop
if quackCompiler $1; then
    :
else
    :
    exit
fi

FILENAME=$(basename "$1")
FILENAME="${FILENAME%.*}"
echo ${CC} Builtins.o ${FILENAME}.c ${CFLAGS} -o ${FILENAME}
${CC} Builtins.o ${FILENAME}.c ${CFLAGS} -o ${FILENAME}
echo ./${FILENAME}
./${FILENAME}
