#!/bin/bash
CC=gcc
CFLAGS="-w -I/home/users/srasmus2/studious-LCW/introCompilers/AST/final"
QUACKC=/home/users/srasmus2/studious-LCW/introCompilers/AST/final/quackCompiler

# If everything compiled correctly generate c code, else stop
if ${QUACKC} $1; then
    :
else
    :
    exit
fi

FILENAME=$(basename "$1")
FILENAME="${FILENAME%.*}"
echo ${CC} Builtins.o ${FILENAME}.c ${CFLAGS} -o ${FILENAME}
${CC} Builtins.o ${FILENAME}.c ${CFLAGS} -o ${FILENAME}
echo ./${FILENAME}
./${FILENAME}
